- name: Install a webserver
  hosts: all
  tasks:
    - name: Install Web Server 
      package:
        name: httpd
        state: present

    - name: Start httpd 
      service:
        name: httpd 
        state: started 
